# OpenAPI Contract: RAG Query Endpoint

```yaml
openapi: 3.0.1
info:
  title: RAG Query API
  description: API for querying textbook content using Retrieval-Augmented Generation
  version: 1.0.0
paths:
  /api/rag/query:
    post:
      summary: Query textbook content using RAG
      description: Process a user query against textbook content using RAG pipeline with Cohere, Qdrant, and Gemini
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - query
              properties:
                query:
                  type: string
                  description: The user's question about textbook content
                  example: "What are the key principles of humanoid robotics?"
                max_chunks:
                  type: integer
                  description: Maximum number of text chunks to retrieve (default: 5)
                  minimum: 1
                  maximum: 10
                  default: 5
                similarity_threshold:
                  type: number
                  description: Minimum similarity score for retrieved chunks (default: 0.5)
                  minimum: 0.0
                  maximum: 1.0
                  default: 0.5
      responses:
        '200':
          description: Successful response with textbook-based answer
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RAGResponse'
        '400':
          description: Bad request - invalid input parameters
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
components:
  schemas:
    RAGResponse:
      type: object
      required:
        - answer
        - citations
        - chunks_used
        - query
        - timestamp
      properties:
        answer:
          type: string
          description: The answer generated by the LLM based on retrieved context
          example: "Humanoid robotics is based on several key principles including bipedal locomotion, human-like manipulation, and bio-inspired control systems..."
        citations:
          type: array
          items:
            type: object
            required:
              - text
              - source
            properties:
              text:
                type: string
                description: The citation text in IEEE format
                example: "[1] K. S. Fu, R. C. Gonzalez, and C. S. G. Lee, Robotics: Control, Sensing, Vision, and Intelligence. McGraw-Hill, 1987."
              source:
                type: string
                description: Source identifier
                example: "Fu et al. - Robotics Control Sensing Vision and Intelligence"
              url:
                type: string
                description: URL to the source
                example: "https://example.com/textbook/chapter1"
        chunks_used:
          type: array
          items:
            $ref: '#/components/schemas/TextChunk'
        query:
          type: string
          description: The original user query
          example: "What are the key principles of humanoid robotics?"
        timestamp:
          type: string
          format: date-time
          description: ISO 8601 timestamp of the response
          example: "2025-12-19T10:30:00Z"
    TextChunk:
      type: object
      required:
        - id
        - content
        - metadata
        - similarity_score
      properties:
        id:
          type: string
          description: Unique identifier for the chunk
          example: "chunk_001"
        content:
          type: string
          description: The actual text content of the chunk
          example: "Humanoid robots are robots that are designed to look and/or behave like humans. They typically have a head, a torso, two arms, and two legs..."
        metadata:
          type: object
          properties:
            source:
              type: string
              description: Source document or section
              example: "textbook/chapter1.md"
            page_number:
              type: integer
              description: Page number in the source
              example: 42
            section_title:
              type: string
              description: Title of the section
              example: "Introduction to Humanoid Robotics"
            url:
              type: string
              description: URL reference to the source
              example: "https://example.com/textbook/chapter1"
            citation:
              type: string
              description: IEEE-formatted citation
              example: "[1] K. S. Fu, R. C. Gonzalez, and C. S. G. Lee, Robotics: Control, Sensing, Vision, and Intelligence. McGraw-Hill, 1987."
        similarity_score:
          type: number
          description: Similarity score relative to the query
          minimum: 0.0
          maximum: 1.0
          example: 0.85
    ErrorResponse:
      type: object
      required:
        - error
        - code
      properties:
        error:
          type: string
          description: Error message
          example: "Invalid query parameter"
        code:
          type: string
          description: Error code
          example: "INVALID_QUERY"
        details:
          type: object
          description: Additional error details
          example: {"query": "must not be empty"}
```