from datetime import datetime
from typing import List, Optional
from pydantic import BaseModel
from .retrieved_chunk import RetrievedChunk

class GroundedResponse(BaseModel):
    """
    Model representing an answer generated by the agent that contains only information
    present in the retrieved document chunks
    """
    response_text: str
    source_chunks: List[RetrievedChunk] = []
    confidence_score: Optional[float] = None
    timestamp: datetime = datetime.now()

    def __str__(self):
        """String representation of the response"""
        return f"Response(text='{self.response_text[:100]}...', confidence={self.confidence_score})"

    def is_fully_grounded(self) -> bool:
        """
        Check if the response is fully grounded in the source chunks.
        This would require more sophisticated content analysis in a real implementation.
        """
        # For now, we consider it grounded if it has source chunks
        return len(self.source_chunks) > 0

    def calculate_confidence(self) -> float:
        """
        Calculate confidence based on the average score of source chunks
        """
        if not self.source_chunks:
            return 0.0

        avg_score = sum(chunk.score for chunk in self.source_chunks) / len(self.source_chunks)
        return avg_score